version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db_name"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pddata:/var/lib/postgresql/data

  redis:
    image: redis:6.0-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build:
      context: .
    command: celery -A goodhabit worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    env_file:
      - .env

  celery-beat:
    build:
      context: .
    command: celery -A goodhabit beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      celery:
        condition: service_started
      redis:
        condition: service_started

volumes:
  redis_data:
  pddata:
